version: 2
jobs:
  test:
    docker:
      - image: circleci/node:4-browsers
        environment:
          - NPM_CONFIG_PROGRESS=false
          - NPM_CONFIG_SPIN=false
          - SAUCE_ACCESS_KEY="80dcffc2-c9a2-45e2-9fb7-87b29a6cd986"
          - SAUCE_USERNAME="segment-oss"
          - TEST_REPORTS_DIR="$CIRCLE_TEST_REPORTS"
    steps:
      - checkout
      - run:
          name: Login to npm
          command: |
            npm config set "//registry.npmjs.org/:_authToken" $NPM_AUTH
            yarn add codecov
      - run:
          name: Install dependencies
          command: yarn install
      - run:
          name: Run tests
          command: make test
      - store_artifacts:
          path: coverage
      - run:
          name: Run coverage
          command: ./node_modules/.bin/codecov
  deploy:
    docker:
      - image: circleci/node:4-browsers
    steps:
      - checkout
      - run:
          name: Login to npm
          command: |
            npm config set "//registry.npmjs.org/:_authToken" $NPM_AUTH
            yarn add codecov
      - run:
          name: Publish to npm
          command: npm publish .
workflows:
  version: 2
  test_and_publish:
    jobs:
      - test
      - deploy:
          requires:
            - test
          filters:
            tags: 
              only: /[0-9]+(\.[0-9]+)*(-.+)?/

